### ISSUE TITLE
[Bug]: Error on Image Add in version 6.4.3 NPM Package and no documentation available for new FabricImage

### ISSUE THREAD

**Issue by RobHedley** [fabricjs/fabric.js#10200]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome, Safari

### Node Version (if applicable)

None

### Link To Reproduction

I cannot create a reproduction as the issue causes the app to crash

### Steps To Reproduce

1. Install latest npm FabricJS Package 6.4.3 in a React App
2. Initiate Canvas etc
3. Add Image to the canvas using the new FarbricImage

### Expected Behavior

That the image is added to the canvas in the same way the new FabricText works. I have successfully added Text, using the new FabricText,  and objects to the canvas however FabricText kills the app before I can update the canvas with the error listed below.

### Actual Behavior

I don't even get to the point of running updateAll on the canvas as the app crashes with a TypeError: Cannot read properties of null (reading 'classList') at Qo.setElement.

I have tried to find documentation to this new change (as I am new to FabricJS) to make sure I am not doing anything wrong however I cannot find any reference apart from the breaking changes document.

### Error Message & Stack Trace

```bash
TypeError: Cannot read properties of null (reading 'classList')
    at Qo.setElement (http://localhost:3000/static/js/bundle.js:160422:172)
    at new Qo (http://localhost:3000/static/js/bundle.js:160415:251)
    at http://localhost:3000/static/js/bundle.js:11400:23
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:82913:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:84406:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:84378:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:84368:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:84358:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:86243:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:86195:18)
```

**Comment by RobHedley** [comment]
Apologies, I forgot to add my implementation of FabricImage, please find below:

const backImg = new FabricImage(testImage, {
                  left: 0,
                  top: 0,
                  height: 400,
                  width: 500,
                  selectable: false,
                  hasControls: false,
                  hasBorders: false
                  });
                  
 I have tried testImage as a string URL to the image and an imported React Image Object and I get the same error. I have used FabricText in the same way and it works perfectly. 
 
 If I am doing something stupid then if someone could point me in the right direction as the lack of documentation is a killer.
 
 Thanks and great work on a fantastic repo.

**Comment by RobHedley** [comment]
Apologies for the bity information, I am working on a number of projects at the same time. Here is a code pen showing the issue - https://codepen.io/hedlro/pen/poMNOZq?editors=0110

If you comment out the image Add (FabricImage) then it runs fine and creates the canvas with a grey box and some text (using the new FabricText). If you leave the FabricImage in and look at the console you will see the error message as outlined below. As I said above it may be me doing something wrong but without documentation I cannot check my code.:

TypeError: Cannot read properties of null (reading 'classList')
    at n.setElement (Image.ts:236:13)
    at new n (Image.ts:205:10)
    at pen.js?key=pen.js-c21033cf-1fa4-0e50-5e46-ad783f036434:35:23
    at Mb (react-dom.production.min.js:111:280)
    at Yh (react-dom.production.min.js:121:327)
    at R (react.production.min.js:11:265)
    at va (react.production.min.js:12:403)
    at react.production.min.js:25:14
