### ISSUE TITLE
Building Fabrics.js Fails - Cannot find module 'execSync'

### ISSUE THREAD

**Issue by abuechler** [fabricjs/fabric.js#1275]
Hi there,

trying to build the project with the 'build_all' script gives me an error:

```
$ ./build_all 
building minified src files
creating build.sh with all module combinations (minified and not)

module.js:340
    throw err;
          ^
Error: Cannot find module 'execSync'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/andi/dev/projects/fabric.js/create_build_script.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
removing all previous module files
mkdir: cannot create directory `../fabricjs.com/build/files': No such file or directory
building actual distribution files with all module combinations (minified and not)
removing tmp files
erasing build.sh
```

Although I've got exec-sync installed:

```
$ npm list -g exec-sync
/home/andi/bin/npm/lib
└── exec-sync@0.1.6 
```

**Comment by Bruce12** [comment]
I got this problem too!
