### ISSUE TITLE
Bug - Node.js and Fabric - Error: Image given has not completed loading

### ISSUE THREAD

**Issue by TimHarker** [fabricjs/fabric.js#1894]
When loading an image from a canvas through loadFromJSON and rendering it to an image using createPNGStream...

var http = require('http');
var fabric = require('fabric').fabric;
http.createServer(function (request, response) {
    var body = "";
    request.on('data', function (chunk) {
        body += chunk;
    });
    request.on('end', function () {
        var canvas = fabric.createCanvasForNode(1600, 903);
        response.writeHead(200, { 'Content-Type': 'image/png' });
        console.log(body);
        canvas.loadFromJSON(body, function () {
            canvas.renderAll();
            var stream = canvas.createPNGStream();
            stream.on('data', function (chunk) {
                response.write(chunk);
            });
            stream.on('end', function () {
                response.end();
            });
        });
    });
}).listen(8080);

I get this error...  Any ideas?  Here's the image I'm trying to load... https://xcw.blob.core.windows.net/images/uploaded/mwgllnpogk.jpg

C:\Users\tharker\AppData\Roaming\npm\node_modules\fabric\dist\fabric.js:17387
      elementToDraw && ctx.drawImage(elementToDraw,
                           ^
Error: Image given has not completed loading
    at klass.fabric.Image.fabric.util.createClass._render (C:\Users\tharker\AppData\Roaming\npm\node_modules\fabric\dist\fabric.js:17387:28)
    at klass.fabric.Object.fabric.util.createClass.render (C:\Users\tharker\AppData\Roaming\npm\node_modules\fabric\dist\fabric.js:11432:12)
    at klass.fabric.StaticCanvas.fabric.util.createClass._draw (C:\Users\tharker\AppData\Roaming\npm\node_modules\fabric\dist\fabric.js:6358:16)
    at klass.fabric.StaticCanvas.fabric.util.createClass._renderObjects (C:\Users\tharker\AppData\Roaming\npm\node_modules\fabric\dist\fabric.js:6496:16)
    at klass.fabric.StaticCanvas.fabric.util.createClass.renderAll (C:\Users\tharker\AppData\Roaming\npm\node_modules\fabric\dist\fabric.js:6467:12)
    at C:\Users\tharker\AppData\Roaming\npm\helloworld.js:17:20
    at klass.fabric.util.object.extend._setBgOverlay (C:\Users\tharker\AppData\Roaming\npm\node_modules\fabric\dist\fabric.js:10303:19)
    at C:\Users\tharker\AppData\Roaming\npm\node_modules\fabric\dist\fabric.js:10282:13
    at C:\Users\tharker\AppData\Roaming\npm\node_modules\fabric\dist\fabric.js:10375:19
    at onLoaded (C:\Users\tharker\AppData\Roaming\npm\node_modules\fabric\dist\fabric.js:603:23)

**Comment by coolfeature** [comment]
This may help: http://stackoverflow.com/a/35994011/2779183
