### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by ArturBaybulatov** [fabricjs/fabric.js#5301]
## Version

2.4.1

## Information about environment

```
> node --version
v8.11.2

> npm --version
5.6.0

> systeminfo | findstr /B /C:"OS Name" /C:"System Type"
OS Name:                   Microsoft Windows 10 Pro
System Type:               x64-based PC

> python --version
Python 3.6.4

> where libcairo-2.dll
C:\GTK\bin\libcairo-2.dll
```

## Steps to reproduce

Run `npm install`

## Expected Behavior

Dependencies install

## Actual Behavior

```
C:\Users\Baybulatov.Artur\AppData\Local\Temp\ggg\fabric.js>npm install

> canvas@1.6.13 install C:\Users\Baybulatov.Artur\AppData\Local\Temp\ggg\fabric.js\node_modules\canvas
> node-gyp rebuild


C:\Users\Baybulatov.Artur\AppData\Local\Temp\ggg\fabric.js\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\prog\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\prog\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Baybulatov.Artur\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\prog\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\prog\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\prog\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\prog\\nodejs\\node.exe" "C:\\prog\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Baybulatov.Artur\AppData\Local\Temp\ggg\fabric.js\node_modules\canvas
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.13 (node_modules\canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.13 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

up to date in 7.955s
```

**Comment by asturur** [comment]
Installation is not failing, is skipping canvas.
If you need canvas to work with fabricJS on node, you have to visiti node-canvas github repository and get help with installing the prerequisites.
