### ISSUE TITLE
Can't do server side rendering 

### ISSUE THREAD

**Issue by vigalo** [fabricjs/fabric.js#5388]
Hello :

I have an Ionic app that uses fabricjs 2.2.4. It works like a charm.
The fabric canvas are serialized and saved in the server through a rest api (node-express-feathers).
Now, I need to do server side rendering to generate png's from the serialized data as in documentation.
I installed the same version of fabricjs (2.2.4) under node (8.11.1) .
The sugested commands :

> node
...
> typeof require('canvas'); // "function"
> typeof require('fabric'); // "object"

work as expected. I tried to run the  'hellow world' as sugested in tutorial : 

`var fs = require('fs'),
    fabric = require('fabric').fabric,
    out = fs.createWriteStream(__dirname + '/helloworld.png');

var canvas = fabric.createCanvasForNode(200, 200);
var text = new fabric.Text('Hello world', {
  left: 100,
  top: 100,
  fill: '#f55',
  angle: 15
});
canvas.add(text);

var stream = canvas.createPNGStream();
stream.on('data', function(chunk) {
  out.write(chunk);
});`

Previously, I changed createCanvasForNode to fabric.staticCanvas, but it throws this error : 

 node testfabric.js                     /var/www/feathers-server/node_modules/fabric/dist/fabric.js:1033
            this.initialize.apply(this, arguments);
                            ^

TypeError: Cannot read property 'apply' of undefined
    at Object.klass [as Canvas] (/var/www/feathers-server/node_modules/fabric/dist/fabric.js:1033:29)
    at Object.<anonymous> (/var/www/feathers-server/testfabric.js:4:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

Can you help me?
Thanks.

**Comment by vigalo** [comment]
Solved. My bad. I tried many things and was using incorrect parameters in fabric.staticCanvas.
Thanks
