### ISSUE TITLE
 An error occurs at npm test after npm build_with_gestures

### ISSUE THREAD

**Issue by hanjisun** [fabricjs/fabric.js#5518]
Hi, I tried

step 1. git clone fabric.js project in my desktop
step 2. `npm install`
step 3. `npm run build_with_gestures`
step 4. `npm run test`

It was successful until step 3, but there is an error in step 4.
```
not ok 1 test/node_test_setup.js > Failed to load the test file with error:
ReferenceError: window is not defined
    at /Users/admin/develop/fabric/v2.6.0/fabric.js/dist/fabric.js:9:28429
    at /Users/admin/develop/fabric/v2.6.0/fabric.js/dist/fabric.js:9:29094
    at Object.<anonymous> (/Users/admin/develop/fabric/v2.6.0/fabric.js/dist/fabric.js:9:36892)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/admin/develop/fabric/v2.6.0/fabric.js/node_modules/istanbul/lib/hook.js:107:24)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

  ---
  message: "should be able to load file"
  severity: failed
  actual: false
  expected: true
  stack:     at Object.<anonymous> (/Users/admin/develop/fabric/v2.6.0/fabric.js/node_modules/qunit/bin/run.js:61:13)
  

..... etc...

# pass 0
# skip 0
# todo 0
# fail 306

=============================== Coverage summary ===============================
Statements   : 1.88% ( 179/9546 )
Branches     : 0.31% ( 19/6167 )
Functions    : 0.13% ( 2/1523 )
Lines        : 1.89% ( 178/9420 )
================================================================================

```

However, the `npm run test` is successful when the `npm run build `

node is v7.10.1
npm is v4.2.0 
fabric.js is v2.6.0

Is it just me? Please somebody help me.

**Comment by asturur** [comment]
the gesture lib is probably making some use of window straight forward that does not allow node tests to run.

**Comment by asturur** [comment]
you cloned the repo, on what commit did you set yourselft up to get fabric 2.6.0?
Why not the lastest from the 2.x versions?

**Comment by asturur** [comment]
Did not notice this issue is 1.5 years old.
