### ISSUE TITLE
fabric.util.loadImage fail on Node

### ISSUE THREAD

**Issue by Clemweb** [fabricjs/fabric.js#5724]
## Version
3.0.0

## Information about environment
Nodejs 10.15.3

## Steps to reproduce
Run a script with 

`fabric.util.loadImage(req.body.mainDir + 'txt-' + txtID + '.png', function (img) {
                                    req.oImg = new fabric.Image(img);`

## Expected Behavior
Correct image object

## Actual Behavior
Node error :

Error: Could not load img: "/var/www/html/ve/public_html/web/_shop/products/1/docs/2629/txt-ctzTxt1.png"
    at onErrorWrapped (/var/www/html/ve/public_html/vendor/custengine/lib/node_modules/fabric/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:38:19)
    at Object.check (/var/www/html/ve/public_html/vendor/custengine/lib/node_modules/fabric/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:72:23)
    at Promise.resolve.then (/var/www/html/ve/public_html/vendor/custengine/lib/node_modules/fabric/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:83:27)
    at process._tickCallback (internal/process/next_tick.js:68:7) Error: Tried to fetch invalid URL /var/www/html/ve/public_html/web/_shop/products/1/docs/2629/txt-ctzTxt1.png
    at ResourceLoader.fetch (/var/www/html/ve/public_html/vendor/custengine/lib/node_modules/fabric/node_modules/jsdom/lib/jsdom/browser/resources/resource-loader.js:84:29)
    at PerDocumentResourceLoader.fetch (/var/www/html/ve/public_html/vendor/custengine/lib/node_modules/fabric/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:17:42)
    at HTMLImageElementImpl._attrModified (/var/www/html/ve/public_html/vendor/custengine/lib/node_modules/fabric/node_modules/jsdom/lib/jsdom/living/nodes/HTMLImageElement-impl.js:39:36)
    at Object.exports.appendAttribute (/var/www/html/ve/public_html/vendor/custengine/lib/node_modules/fabric/node_modules/jsdom/lib/jsdom/living/attributes.js:62:11)
    at Object.exports.setAttributeValue (/var/www/html/ve/public_html/vendor/custengine/lib/node_modules/fabric/node_modules/jsdom/lib/jsdom/living/attributes.js:218:13)
    at HTMLImageElementImpl.setAttributeNS (/var/www/html/ve/public_html/vendor/custengine/lib/node_modules/fabric/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:251:16)
    at HTMLImageElementImpl.set src [as src] (/var/www/html/ve/public_html/vendor/custengine/lib/node_modules/fabric/node_modules/jsdom/lib/jsdom/living/nodes/HTMLImageElement-impl.js:61:10)
    at HTMLImageElement.set src [as src] (/var/www/html/ve/public_html/vendor/custengine/lib/node_modules/fabric/node_modules/jsdom/lib/jsdom/living/generated/HTMLImageElement.js:52:23)
    at Object.loadImage (/var/www/html/ve/public_html/vendor/custengine/lib/node_modules/fabric/dist/fabric.js:987:15)
    at /var/www/html/ve/public_html/vendor/custengine/lib/node.js:267:45

Works fine on Fabricjs 1.7

**Comment by asturur** [comment]
you cannot load with jsdom files like that. try to use the file protocol like you would do in the address bar of a browser. 'file:///'
