### ISSUE TITLE
loading an local image 

### ISSUE THREAD

**Issue by kristianAndersen** [fabricjs/fabric.js#5864]
Hello 
I am using Fabric in node.js, and i am trying to load an image from a folder in my project,
but it wont work! unless i load from a url no problems?

```
 var src =__dirname+'./superliga/2019_dli_odd_XXX_app_push_ios_1000x1000.png';
fabric.util.loadImage(src, function(img) {
 
  var oImg = new fabric.Image(img);
  console.log(img.src)
  
  oImg.set({
    left: 0,
    top: 0,
    width:1000,
    height:1000,
    originX: 'center',
    originY: 'center',
    transparentCorners: false
  });
  canvas.add(oImg);
  canvas.renderAll();
```

i get this error

```
Error: Could not load img: "2019_dli_odd_XXX_app_push_ios_1000x1000.png"
    at onErrorWrapped (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:38:19)
    at Object.check (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:72:23)
    at request.then.catch.err (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:124:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3) Error: Tried to fetch invalid URL 2019_dli_odd_XXX_app_push_ios_1000x1000.png
    at ResourceLoader.fetch (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/browser/resources/resource-loader.js:84:29)
    at PerDocumentResourceLoader.fetch (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:17:42)
    at HTMLImageElementImpl._attrModified (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/living/nodes/HTMLImageElement-impl.js:39:36)
    at Object.exports.appendAttribute (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/living/attributes.js:62:11)
    at Object.exports.setAttributeValue (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/living/attributes.js:218:13)
    at HTMLImageElementImpl.setAttributeNS (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:251:16)
    at HTMLImageElementImpl.set src [as src] (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/living/nodes/HTMLImageElement-impl.js:61:10)
    at HTMLImageElement.set src [as src] (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/living/generated/HTMLImageElement.js:52:23)
    at Object.loadImage (/Users/awesome/Dropbox/2019/swatter/node_modules/fabric/dist/fabric.js:992:15)
    at Object.<anonymous> (/Users/awesome/Dropbox/2019/swatter/index.js:72:13)
Error: Uncaught [TypeError: Cannot read property 'naturalWidth' of null]
    at reportException (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
    at Timeout.callback [as _onTimeout] (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/browser/Window.js:673:7)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) TypeError: Cannot read property 'naturalWidth' of null
    at klass._renderFill (/Users/awesome/Dropbox/2019/swatter/node_modules/fabric/dist/fabric.js:20378:39)
    at klass._renderPaintInOrder (/Users/awesome/Dropbox/2019/swatter/node_modules/fabric/dist/fabric.js:14158:14)
    at klass._render (/Users/awesome/Dropbox/2019/swatter/node_modules/fabric/dist/fabric.js:20357:12)
    at klass.drawObject (/Users/awesome/Dropbox/2019/swatter/node_modules/fabric/dist/fabric.js:13901:12)
    at klass.render (/Users/awesome/Dropbox/2019/swatter/node_modules/fabric/dist/fabric.js:13756:14)
    at klass._renderObjects (/Users/awesome/Dropbox/2019/swatter/node_modules/fabric/dist/fabric.js:7585:34)
    at klass.renderCanvas (/Users/awesome/Dropbox/2019/swatter/node_modules/fabric/dist/fabric.js:7537:12)
    at klass.renderAll (/Users/awesome/Dropbox/2019/swatter/node_modules/fabric/dist/fabric.js:7458:12)
    at klass.renderAndReset (/Users/awesome/Dropbox/2019/swatter/node_modules/fabric/dist/fabric.js:7474:12)
    at Timeout.callback [as _onTimeout] (/Users/awesome/Dropbox/2019/swatter/node_modules/jsdom/lib/jsdom/browser/Window.js:671:19)
```

**Comment by asturur** [comment]
https://stackoverflow.com/questions/57713832/load-images-from-local-directory-in-fabric/57747145#57747145

does this question and answer help?

**Comment by kristianAndersen** [comment]
@asturur Thanks a million :) 

so changing this 
 `var src =__dirname+'./superliga/2019_dli_odd_XXX_app_push_ios_1000x1000.png';`
to this , _and bob is your uncle_ 
 ` var src ='file://'+__dirname+'/superliga/2019_dli_odd_XXX_app_push_ios_1000x1000.png';`
