### ISSUE TITLE
canvas.node is not a valid Win32 application

### ISSUE THREAD

**Issue by kirill-chirkov-at-clouty** [fabricjs/fabric.js#5914]
## Version
3.4.0

## Information about environment
Windows 10 ultimate x64
Node v10.13.0 or Node v12.11.1
Angular server environment

## Steps to reproduce
1. Install Cairo like installation process asked to (using `msys`)
2. Install fabric
3. Write any code with fabric import
4. Build application using webpack. Since canvas.node needs to be loaded, I used [native ext loader](https://github.com/smt116/node-native-ext-loader) like this:
```
node: {
    __dirname: true // Used for native-ext-loader to resolve path correctly
},
...
{
        test: /\.node$/,
        loader: "native-ext-loader",
        options: {
          rewritePath: path.resolve(__dirname, "dist")
        }
}
```
This is the only lines I added so webpack can build without errors
5. Run application with node and receive error in runtime:
```
Error: Uncaught (in promise): Error: Cannot open D:\Projects\frontend\dist\canvas.node: Error: D:\Projects\frontend\dist\canvas.node is not a valid Win32 application.
```

On this path there is an actual `canvas.node` file from `node_modules/canvas/build/Release/canvas.node` which was copied by webpack loader I used before.

## Expected Behavior
To work in runtime without errors

**Comment by asturur** [comment]
if you are building with webpack i assume you want to run fabricJS on the browser.
If this assumption is correct, please look a this example repo

https://github.com/fabricjs/fabricjs-webpack

where there is an example webpack configuration to load fabricjs without native extensions in the bundle.

So to recap, if you are targeting the browser:
- you do not need to install nodecanvas ( unless you plan to use it with jest for tests )
- you do not need to load nodecanvas in webpack ( check the example )

If you are targeting node environment for fabricjs:
- i do not know what to say, because i do not know why webpack is needed there

**Comment by kirill-chirkov-at-clouty** [comment]
I use webpack for server to enable server rendering for Angular. I do not have any intention to use fabricjs there, but I can't deimport it. And since it imports, it tries to load canvas and gives error in runtime.

So I added these 6 externals to webpack config and now it gives me `Error: Uncaught (in promise): TypeError: Cannot read property 'JSDOM' of null`.

**Comment by asturur** [comment]
Can you give more context on where the error happens?

**Comment by kirill-chirkov-at-clouty** [comment]
Judging by error, it is this line https://github.com/fabricjs/fabric.js/blob/e4db8ec8ab97ce5c85923e733638fc33510ccdb2/HEADER.js#L24

**Comment by kirill-chirkov-at-clouty** [comment]
Here's the stack
```
TypeError: Cannot read property 'JSDOM' of null
    at Object.module.exports (D:\Projects\frontend\dist\server.js:186219:33)
    at __webpack_require__ (D:\Projects\frontend\dist\server.js:20:30)
    at Object.DMZp (D:\Projects\frontend\dist\server.js:165624:961246)
    at __webpack_require__ (D:\Projects\frontend\dist\server.js:165624:295)
    at Object.0c3/ (D:\Projects\frontend\dist\server.js:165624:165442)
    at __webpack_require__ (D:\Projects\frontend\dist\server.js:165624:295)
    at Object.qn+G (D:\Projects\frontend\dist\server.js:165624:3433068)
    at __webpack_require__ (D:\Projects\frontend\dist\server.js:165624:295)
    at Object.IgEE (D:\Projects\frontend\dist\server.js:165624:1316505)
    at __webpack_require__ (D:\Projects\frontend\dist\server.js:165624:295)
    at resolvePromise (D:\Projects\frontend\dist\server.js:163981:35)
    at resolvePromise (D:\Projects\frontend\dist\server.js:163940:21)
    at D:\Projects\frontend\dist\server.js:164042:21
    at ZoneDelegate.invokeTask (D:\Projects\frontend\dist\server.js:163576:35)
    at Object.onInvokeTask (D:\Projects\frontend\dist\server.js:27065:33)
    at ZoneDelegate.invokeTask (D:\Projects\frontend\dist\server.js:163575:40)
    at Zone.runTask (D:\Projects\frontend\dist\server.js:163343:51)
    at drainMicroTaskQueue (D:\Projects\frontend\dist\server.js:163756:39)
    at ZoneTask.invokeTask (D:\Projects\frontend\dist\server.js:163662:25)
    at ZoneTask.invoke (D:\Projects\frontend\dist\server.js:163647:52)
```

**Comment by asturur** [comment]
probably since we switched to JSDOM 15 we need to update the example in webpack
let me check it.

**Comment by kirill-chirkov-at-clouty** [comment]
I wonder about current status. Is this possible just to meddle with webpack config to get this working?

**Comment by asturur** [comment]
Sorry for not getting back to you. Yes is possible to make it work with webpack, i have it in a production app, so i know it can be done.

**Comment by asturur** [comment]
@kirill-chirkov-at-clouty i made a branch on the config repository to show the new config:

https://github.com/fabricjs/fabricjs-webpack

Please have a look at the canvas2-webpack4 branch.
