### ISSUE TITLE
TypeError on initializing StaticCanvas

### ISSUE THREAD

**Issue by meetmangukiya** [fabricjs/fabric.js#6190]
## Version
4.0.0-beta.7

## Test Case
Example from "Fabric on Node.js" on http://fabricjs.com/fabric-intro-part-4

```js
var fs = require('fs'),
    fabric = require('fabric').fabric,
    out = fs.createWriteStream(__dirname + '/helloworld.png');

var canvas = new fabric.StaticCanvas(null, { width: 500, height: 500 });
var text = new fabric.Text('Hello world', {
  left: 100,
  top: 100,
  fill: '#f55',
  angle: 15
});
canvas.add(text);

var stream = canvas.createPNGStream();
stream.on('data', function(chunk) {
  out.write(chunk);
});
```

## Information about environment
Nodejs v12.14.0

## Steps to reproduce
Run the provided code as script

## Expected Behavior
Output png file

## Actual Behavior

TypeError: Cannot read property 'apply' of undefined

```
node_modules/fabric/dist/fabric.js:2199
      this.initialize.apply(this, arguments);
                      ^

TypeError: Cannot read property 'apply' of undefined
    at Object.klass [as Canvas] (node_modules/fabric/dist/fabric.js:2199:23)
    at Object.<anonymous> (test2.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
```

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/76166802-a4090d00-6161-11ea-84ae-d15ab310c2fb.png)

no error for me on node 12.14.1
Are you sure you got node-canvas correctly installed?

**Comment by meetmangukiya** [comment]
I tried installing and running in a new directory, didn't get this error, weird. Sorry about creating this issue. Thanks!
