### ISSUE TITLE
require(...).jsdom is not a function

### ISSUE THREAD

**Issue by BannerBomb** [fabricjs/fabric.js#6260]
## Version
1.7.22

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser? Nodejs v13.0.1
Which browsers? N/A

## Steps to reproduce
Install fabric using `npm i github:fabricjs/fabric.js#1.x` then run `require('fabric')`

## Actual Behavior
```
TypeError: require(...).jsdom is not a function
    at Object.<anonymous> (/opt/rookiebotelite/node_modules/fabric/dist/fabric.js:18:6)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:70:39)
    at require (internal/modules/cjs/helpers.js:74:18)
    at eval (eval at eval (/opt/rookiebotelite/src/commands/Admin/eval.js:109:13), <anonymous>:1:1)
    at module.exports.eval (/opt/rookiebotelite/src/commands/Admin/eval.js:109:13)
```

I do have jsdom installed

**Comment by asturur** [comment]
What JSDOM do you have installed? is it the 9.14 version fabricJS needs?

**Comment by BannerBomb** [comment]
16.2.1 is what I had

**Comment by asturur** [comment]
fabricjs requires the 9.14, it would be better you find a way to use 9.14 or update to fabric 3 that uses a more modern version of it.
