### ISSUE TITLE
TypeError: Cannot set property 'userSelect' of undefined

### ISSUE THREAD

**Issue by okeoke85** [fabricjs/fabric.js#7566]
I'm using fabric on node side and got the error below; it happens when i add fabric.Text, when i just use fabric.Rect there is no problem. I'm trying to load json data that is created on client side, on server side.

TypeError: Cannot set property 'userSelect' of undefined
>      at Object.makeElementUnselectable (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:3331:35)
>      at klass._applyCanvasStyle (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:12227:19)
>      at klass._createLowerCanvas (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:9047:14)
>      at klass._initStatic (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:8724:12)
>      at klass.initialize (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:11306:12)
>      at new klass (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:2958:23)
>      at C:\Development\hemsor\functions\lib\handler\test-paper.handler.js:96:22

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/orhan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/orhan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Client   Code | Server Code | JSON(created in   client and sent the server) | Result
-- | -- | -- | --
this.fabricCanvas = new   fabric.Canvas("canvasID");          var rect = new LX.fabric.Rect({               left: 100,               top: 100,               fill: 'red',               width: 20,               height: 20       }); | let   canvas: any = createCanvas(500, 700);                     canvas = new   LX.fabric.StaticCanvas(canvas, { width: 500, height: 700 });                     canvas.loadFromJSON(json,   (canvas: any) => {}); | {"version":"4.6.0","objects":[{"type":"rect","version":"4.6.0","originX":"left","originY":"top","left":100,"top":100,"width":20,"height":20,"fill":"red","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeDashOffset":0,"strokeLineJoin":"miter","strokeUniform":false,"strokeMiterLimit":4,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","skewX":0,"skewY":0,"rx":0,"ry":0}]} | Works fine
this.fabricCanvas.add(             new   fabric.Text("foo", {               fontFamily:   "Delicious_500",               left: 100,               top: 100             })           ); | let   canvas: any = createCanvas(500, 700);                     canvas = new   LX.fabric.StaticCanvas(canvas, { width: 500, height: 700 });                     canvas.loadFromJSON(json,   (canvas: any) => {}); | {"version":"4.6.0","objects":[{"type":"text","version":"4.6.0","originX":"left","originY":"top","left":100,"top":100,"width":53.32,"height":45.2,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeDashOffset":0,"strokeLineJoin":"miter","strokeUniform":false,"strokeMiterLimit":4,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","skewX":0,"skewY":0,"fontFamily":"Delicious_500","fontWeight":"normal","fontSize":40,"text":"foo","underline":false,"overline":false,"linethrough":false,"textAlign":"left","fontStyle":"normal","lineHeight":1.16,"textBackgroundColor":"","charSpacing":0,"styles":{},"direction":"ltr","path":null,"pathStartOffset":0,"pathSide":"left"}]} | (process:14036):   Pango-WARNING **: 13:48:18.528: couldn't load font "Delicious_500   Not-Rotated 400px", falling back to "Sans Not-Rotated 400px",   expect ugly output.     >     >  (process:14036): Pango-WARNING   **: 13:48:18.534: couldn't load font "Delicious_500 400px", falling   back to "Sans 400px", expect ugly output.     >  TypeError:   ctx.canvas.setAttribute is not a function     >      at klass._renderChars   (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26526:20)     >      at klass._renderTextLine   (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26086:12)     >      at klass._renderTextCommon   (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26451:14)     >      at klass._renderTextFill   (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26473:12)     >      at klass._renderText   (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26038:14)     >      at klass._render   (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26023:12)     >      at klass.drawObject   (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:15305:12)     >      at klass.render   (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:15163:14)     >      at klass.callSuper   (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:2939:22)     >      at klass.render   (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26993:12)

</body>

</html>

https://github.com/fabricjs/fabric.js/issues/5360#issuecomment-441730840

**Comment by okeoke85** [comment]
And when i use StaticCanvas instead of Canvas i get the error below, maybe it will help;

>  TypeError: ctx.canvas.setAttribute is not a function
>      at klass._renderChars (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26526:20)
>      at klass._renderTextLine (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26086:12)
>      at klass._renderTextCommon (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26451:14)
>      at klass._renderTextFill (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26473:12)
>      at klass._renderText (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26038:14)
>      at klass._render (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26023:12)
>      at klass.drawObject (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:15305:12)
>      at klass.render (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:15163:14)
>      at klass.callSuper (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:2939:22)
>      at klass.render (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26993:12)
