### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'clearRect')

### ISSUE THREAD

**Issue by mikhailnathanielabordo** [fabricjs/fabric.js#8071]
Hi, not sure if this is related but I'm currently encountering `TypeError: Cannot read properties of undefined (reading 'clearRect')` after updating the version to `5.2.1`  it fails on unit testing. but the application seems to be working correctly. 🤔 

I'm also updating from React 16 > React 17. 

```
ImageAnnotationPanel › renders without crashing

    TypeError: Cannot read properties of undefined (reading 'clearRect')

      480 |     const { imageUrl } = this.props;
      481 |
    > 482 |     this.canvas.clear();
          |                 ^
      483 |     this.initAlwaysActiveTools();
      484 |     this.canvas.setBackgroundImage(imageUrl, this.resetCanvas);
      485 |   }

      at klass.clearContext (node_modules/fabric/dist/fabric.js:9567:11)
      at klass.clear (node_modules/fabric/dist/fabric.js:12753:12)
      at klass.clear (node_modules/fabric/dist/fabric.js:2987:52)
      at ImageAnnotationPanel.loadImage (src/components/Workspace/ImageAnnotation/ImageAnnotationPanel.tsx:482:17)
      at ImageAnnotationPanel.componentDidMount (src/components/Workspace/ImageAnnotation/ImageAnnotationPanel.tsx:172:10)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:20663:24)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:23426:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:23151:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22990:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22329:3)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at Object.<anonymous> (src/components/Workspace/ImageAnnotation/ImageAnnotationPanel.test.tsx:88:14)
```

**Comment by ShaMan123** [comment]
duplicate #7876 
solved by #7885

**Comment by ShaMan123** [comment]
In react you need to cleanup after yourself in a `useEffect` hook

**Comment by CookedApps** [comment]
@ShaMan123 What's the correct way to cleanup after yourself?

**Comment by ShaMan123** [comment]
I wash my hands after the bathroom and before I eat, shower and brush teeth daily, floss... 🤣
Pickup clothes?
How about you? 


--- 
I had to

`Canvas#dispose` is the right way.
make sure you don't have any non fabric events that point to fabric etc.
It's a practice not related to fabric but general

**Comment by CookedApps** [comment]
Thank you, I finally learned how to take care of myself! 
...and how to clean up fabric.js the right way. 🙏

**Comment by CookedApps** [comment]
I just noticed that we are already disposing the canvas as described, but are still getting this error.

**Comment by ShaMan123** [comment]
I will need more context, a repro...
it depends on the version.
We fixed it not long ago

**Comment by ShaMan123** [comment]
I has been, migrate to v6

**Comment by ShaMan123** [comment]
it should have been fixed
try to gather more info including the trace which is very important
what framework are you using? react? are you disposing the canvas? are you animating? did you try to dispose animations?

**Comment by dilwalashakib** [comment]
TypeError: Cannot read properties of undefined (reading 'clearRect') 

same problem. How can I solve this problem?

**Comment by dilwalashakib** [comment]
useEffect(() => {
        if(!canvasRef.current) return;
        const scaleX = 800 / canvasWidth;
        const scaleY = 450 / canvasHeight;
        const newZoom = Math.min(scaleX, scaleY);

        let initCanvas = new Canvas(canvasRef.current, {
            width: canvasWidth * newZoom,
            height: canvasHeight * newZoom,
            backgroundColor: "#ffffff",
            preserveObjectStacking: true
        });
        setBaseWidth(canvasWidth);
        setBaseHeight(canvasHeight);

        const data = typeof canvasData === "string" ? JSON.parse(canvasData) : canvasData;
        const hasObject = data.objects && data.objects.length > 0;

        if(initCanvas && canvasData && hasObject) {
            initCanvas.clear();
            initCanvas.loadFromJSON(canvasData)
                .then((canvas) => canvas.requestRenderAll())
                .catch((err) => console.log(err));
        } else {
            initCanvas.backgroundColor = data?.background ? data.background : "#ffffff";
            initCanvas.renderAll();
        }
         
        setCanvas(initCanvas);
        
        return () => {
            initCanvas?.clear();
            initCanvas?.dispose();
            initCanvas = null;
        };
    }, []);

**Comment by dilwalashakib** [comment]
Actually I am using Local development mode.
